package game;

import java.awt.Graphics2D;
import java.util.List;

import engine.Ticker;
import engine.Ticker.TickListener;
import engine.controller.Controller;
import engine.model.Config;
import engine.model.Entity;
import engine.model.Model;
import engine.model.Player;
import engine.model.Rock;
import engine.model.Pigeon;
import engine.model.EnemyShooter;
import engine.view.View;
import oop.graphics.Canvas;

import game.model.EnvironmentGenerator;
import game.model.ScoreManager;

public class Game implements TickListener {
  private Canvas m_canvas;
  private Model m_model;
  private View m_view;
  private Controller m_controller;
  private Ticker m_ticker;
  private static final double BASE_SCROLL_SPEED = 4.0; // Base meters per second
  private static final double SPEED_INCREASE_PER_LEVEL = 1.0; // Speed increase per multiplier level
  private double m_scrolledMeters = 0.0;
  private EnvironmentGenerator m_envGen;
  private ScoreManager m_scoreManager;
  private UIManager m_uiManager;
  
  // Player position constants for runner style
  private static final int PLAYER_COL = 2; // Player stays in column 2
  private static final int PLAYER_ROW = 10; // Player stays in row 10 (middle)
  
  // Game state
  private boolean m_gameOver = false;
  private boolean m_gameStarted = false;

  private int frameCounter = 0;

  Game(Canvas canvas, int nrows, int ncols) {
    this.m_canvas = canvas;
    
    Config conf = new Config();
    conf.tore = false; // Disable toroidal wrap for side-scrolling
    
    m_model = new Model(nrows, ncols);
    m_model.config(conf); // configure before adding entities
    
    m_view = new View0(canvas, m_model);
    
    // Initialize score manager
    m_scoreManager = ScoreManager.getInstance();
    
    // Initialize UI manager
    m_uiManager = new UIManager(canvas);
    m_uiManager.setGame(this);
    
    // Don't create entities until game starts
    m_controller = new Controller0(canvas, m_model, m_view, m_uiManager);
    
    // Create and start the ticker for game updates
    m_ticker = new Ticker();
    m_ticker.addListener(this); // Listen for ticks directly in Game class
    m_ticker.start(60); // 60 FPS
  }
  
  /**
   * Reset and start a new game
   */
  public void resetGame() {
    System.out.println("=== RESETTING GAME ===");
    
    // Clear existing entities
    List<Entity> entitiesToRemove = new java.util.ArrayList<>();
    java.util.Iterator<Entity> iterReset = m_model.entities();
    while (iterReset.hasNext()) {
      Entity entity = iterReset.next();
      entitiesToRemove.add(entity);
    }
    for (Entity entity : entitiesToRemove) {
      m_model.removeEntity(entity);
    }
    System.out.println("Cleared " + entitiesToRemove.size() + " existing entities");
    
    // Reset game state
    m_gameOver = false;
    m_gameStarted = true;
    m_scrolledMeters = 0.0;
    
    // Reset score manager
    m_scoreManager.reset();
    System.out.println("Score manager reset. Score: " + m_scoreManager.getScore() + ", Time: " + m_scoreManager.getFormattedTime());
    
    // Create new player in fixed position for runner style
    Player player = new Player(m_model, PLAYER_ROW, PLAYER_COL, 0); // Always facing right (0 degrees)
    System.out.println("Created player at (" + PLAYER_ROW + ", " + PLAYER_COL + ")");
    
    // No initial obstacles - let the environment generator create them naturally
    System.out.println("Game started with only the player - obstacles will be generated by environment generator");
    
    // Create new environment generator
    m_envGen = new EnvironmentGenerator(m_model);
    System.out.println("Created environment generator");
    
    System.out.println("=== GAME RESET COMPLETE ===");
    System.out.println("Game state - Started: " + m_gameStarted + ", GameOver: " + m_gameOver);
    System.out.println("UI State: " + m_uiManager.getCurrentState());
  }

  public void paint(Canvas canvas, Graphics2D g) {
    // Always draw UI first to determine what to show
    if (m_uiManager.getCurrentState() == UIManager.UIState.RUNNING && m_gameStarted) {
      // Draw game world
    m_view.paint(canvas, g);
      // Draw game HUD
      drawGameHUD(g);
    }
    
    // Draw UI overlay (start screen, game over screen)
    m_uiManager.drawUI(g);
  }
  
  /**
   * Draw game HUD with player health, score, and time
   */
  private void drawGameHUD(Graphics2D g) {
    Player player = m_model.player();
    if (player == null) return;
    
    // Set HUD text properties
    g.setColor(java.awt.Color.WHITE);
    g.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
    
    // Draw health
    String healthText = "Health: " + "♥".repeat(player.getHealth()) + 
                       " ".repeat(player.getMaxHealth() - player.getHealth());
    g.drawString(healthText, 10, 25);
    
    // Draw score
    String scoreText = "Score: " + m_scoreManager.getScore();
    g.drawString(scoreText, 10, 45);
    
    // Draw time
    String timeText = "Time: " + m_scoreManager.getFormattedTime();
    g.drawString(timeText, 10, 65);
    
    // Draw multiplier if active
    if (m_scoreManager.getMultiplier() > 1.0) {
      String multiplierText = "Multiplier: x" + String.format("%.1f", m_scoreManager.getMultiplier());
      g.drawString(multiplierText, 10, 85);
    }
    
    // Draw invincibility indicator
    if (player.isInvincible()) {
      g.setColor(java.awt.Color.YELLOW);
      g.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
      g.drawString("INVINCIBLE", 10, 105);
    }
  }

  @Override
  public void onTick(double deltaTime) {
    try {
      // ALWAYS print this to verify onTick is being called
      if (frameCounter % 60 == 0) { // Only print every second to avoid spam
        System.out.println("onTick called! Frame: " + frameCounter + ", deltaTime: " + String.format("%.4f", deltaTime) + ", gameStarted: " + m_gameStarted);
      }
      
      frameCounter++;
      
      // Check if we should be running
      if (!m_gameStarted) {
        if (frameCounter % 60 == 0) {
          System.out.println("Game not started yet - skipping update");
        }
        return; // Don't update game logic when not running
      }
      
      // WE ARE NOW RUNNING THE GAME!
      if (frameCounter % 60 == 0) {
        System.out.println("=== GAME RUNNING ===");
        System.out.println("UI State: " + m_uiManager.getCurrentState());
        System.out.println("Game Started: " + m_gameStarted + ", Game Over: " + m_gameOver);
      }
      
      Player player = m_model.player();
      
      // Check for game over
      if (player != null && !player.isAlive()) {
        if (!m_gameOver) {
          m_gameOver = true;
          int finalScore = m_scoreManager.getScore();
          System.out.println("Game Over! Final Score: " + finalScore);
    
          // Notify UI manager of game over
          m_uiManager.onGameOver(finalScore);
          m_gameStarted = false;
        }
        return; // Don't update anything else if game is over
      }
      
      if (m_gameOver) return; // Skip updates if game over
      
      // Update score manager
      m_scoreManager.update(deltaTime);
      
      // Update world scroll speed in model for entities to use
      double currentScrollSpeed = getCurrentScrollSpeed();
      m_model.setWorldScrollSpeed(currentScrollSpeed);
      
      if (frameCounter % 60 == 0 && currentScrollSpeed != BASE_SCROLL_SPEED) {
        System.out.println("World scroll speed: " + String.format("%.1f", currentScrollSpeed) + 
                          " m/s (level " + String.format("%.0f", m_scoreManager.getMultiplier()) + ")");
      }

      // Phase 1: Update all entities' stunts (for player animations)
      int stuntsUpdated = 0;
      java.util.Iterator<Entity> iter = m_model.entities();
      while (iter.hasNext()) {
        Entity entity = iter.next();
        if (entity.stunt != null) {
          int elapsedMs = (int)(deltaTime * 1000);
          entity.stunt.tick(elapsedMs);
          stuntsUpdated++;
      }
    }
    
      // Phase 2: Update model physics (this calls entity.update() on all entities)
      m_model.update(deltaTime);
      
      // Phase 3: Ensure player stays in fixed position (runner-style)
      if (player != null) {
        double targetX = PLAYER_COL * m_model.getCellSizeMeters();
      double currentX = player.getX();
      
      if (Math.abs(currentX - targetX) > 0.1) {
        double deltaX = targetX - currentX;
        m_model.moveByPixels(player, deltaX, 0);
          if (frameCounter % 60 == 0) {
            System.out.println("Corrected player X position by " + String.format("%.3f", deltaX));
          }
      }
    }
    
      // Debug output every second
      if (frameCounter % 60 == 0) {
        int entityCount = 0;
        java.util.List<Entity> entitiesSnapshot = new java.util.ArrayList<>();
        
        // Create snapshot for safe iteration
        java.util.Iterator<Entity> iterCount = m_model.entities();
        while (iterCount.hasNext()) {
          entitiesSnapshot.add(iterCount.next());
        }
        
        // Print entity information - focus on entities with negative X coordinates
        int negativeXCount = 0;
        for (Entity ent : entitiesSnapshot) {
          entityCount++;
          String entityType = ent.getClass().getSimpleName();
          double x = ent.getX();
          double y = ent.getY();
          
          // Always print entities with negative X (they should be removed)
          if (x < 0) {
            negativeXCount++;
            System.out.println("NEGATIVE X: " + entityType + " at X=" + String.format("%.2f", x) + 
                             ", Y=" + String.format("%.2f", y) + 
                             " (velocity=" + String.format("%.1f", ent.getVelocity()) + 
                             ", orientation=" + String.format("%.0f", ent.orientation()) + "°)");
          }
          // Print first few entities normally
          else if (entityCount <= 3) {
            System.out.println("Entity " + entityType + " at X=" + String.format("%.2f", x) + 
                             ", Y=" + String.format("%.2f", y) + 
                             " (velocity=" + String.format("%.1f", ent.getVelocity()) + 
                             ", orientation=" + String.format("%.0f", ent.orientation()) + "°)");
          }
        }
        
        if (negativeXCount > 0) {
          System.out.println("WARNING: " + negativeXCount + " entities have negative X coordinates!");
        }
        
        System.out.println("Total entities: " + entityCount + ", Stunts updated: " + stuntsUpdated);
        System.out.println("Score: " + m_scoreManager.getScore() + ", Time: " + m_scoreManager.getFormattedTime());
      }
      
      // Phase 4: Environment generation and cleanup
      m_scrolledMeters += getCurrentScrollSpeed() * deltaTime;
    double cellSize = m_model.getCellSizeMeters();
      double generationThreshold = cellSize * 0.5;
      
      // Always check for off-screen entities every frame (not just when generating)
      java.util.List<Entity> toRemove = new java.util.ArrayList<>();
      java.util.List<Entity> entitiesSnapshot = new java.util.ArrayList<>();
      
      // Create snapshot first
      java.util.Iterator<Entity> iter3 = m_model.entities();
      while (iter3.hasNext()) {
        entitiesSnapshot.add(iter3.next());
      }
      
      // Check which entities need removal - very aggressive removal threshold
      for (Entity entity : entitiesSnapshot) {
        if (!(entity instanceof Player) && entity.getX() < -1.5) { // More aggressive threshold to prevent piling up
          toRemove.add(entity);
        }
      }
      
      // Remove entities one by one
      for (Entity ent : toRemove) {
        try {
        m_model.removeEntity(ent);
          if (frameCounter % 120 == 0) { // Less frequent logging
            System.out.println("Removed off-screen entity: " + ent.getClass().getSimpleName() + 
                              " at X=" + String.format("%.2f", ent.getX()));
          }
        } catch (Exception e) {
          System.err.println("Error removing entity: " + e.getMessage());
        }
      }
      
      if (toRemove.size() > 0 && frameCounter % 120 == 0) {
        System.out.println("Removed " + toRemove.size() + " off-screen entities");
      }

      // Generate new content when threshold is reached
      if (m_scrolledMeters >= generationThreshold) {
        m_scrolledMeters -= generationThreshold;

        if (m_envGen != null) {
          try {
            m_envGen.generateNextColumn();
          } catch (Exception e) {
            System.err.println("Error generating environment: " + e.getMessage());
          }
        }
      }

      // Phase 5: Repaint the view
      m_canvas.repaint();
      
    } catch (Exception e) {
      System.err.println("Error in Game.onTick: " + e.getMessage());
      e.printStackTrace();
    }
  }

  /**
   * Manually trigger environment generation (for testing)
   */
  public void generateEnvironment() {
    if (m_envGen != null) {
      System.out.println("Manually triggering environment generation...");
      m_envGen.generateNextColumn();
    } else {
      System.out.println("Environment generator is null - cannot generate!");
    }
  }
  
  /**
   * Get current game statistics for debugging
   */
  public String getGameStats() {
    int entityCount = 0;
    java.util.Iterator<Entity> iter = m_model.entities();
    while (iter.hasNext()) {
      iter.next();
      entityCount++;
    }
    
    return String.format("Entities: %d, Scrolled: %.2fm, Score: %d, Time: %s", 
                        entityCount, m_scrolledMeters, 
                        m_scoreManager.getScore(), m_scoreManager.getFormattedTime());
  }

  /**
   * Get current scroll speed based on multiplier level
   */
  private double getCurrentScrollSpeed() {
    double multiplierLevel = m_scoreManager.getMultiplier();
    return BASE_SCROLL_SPEED + (SPEED_INCREASE_PER_LEVEL * (multiplierLevel - 1.0));
  }
  
  /**
   * Get current scroll speed for external access (for entity movement)
   */
  public double getWorldScrollSpeed() {
    return getCurrentScrollSpeed();
  }
} 